apiVersion: v1
kind: Namespace
metadata:
  name: rental-platform
  labels:
    app.kubernetes.io/name: rental-platform
    app.kubernetes.io/part-of: rental-platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
